# Generated by Django 5.0.2 on 2024-02-28 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('url', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('app_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.app_category')),
            ],
        ),
    ]
